/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.escaleraserpiente.interfas;

import com.mycompany.escaleraserpiente.Usuario.Registrar;
import java.awt.CardLayout;
import javax.swing.SwingUtilities;

/**
 *
 * @author drymnz
 */
public class Ventana extends javax.swing.JFrame {
    private CardLayout carpeta;
    
    private MenuPrincipal menuPrincipal = new MenuPrincipal();
    private Registrar registrar = new Registrar();

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        subVentanas();
        
    }
    private void subVentanas(){
       carpeta = (CardLayout) JPanelBase.getLayout();
       JPanelBase.add(menuPrincipal, "MenuPrincipal");
       JPanelBase.add(registrar,"Registrar");
    }
   
    public void subMenuRegistrar(){
        carpeta.show(JPanelBase, "Avion");
        SwingUtilities.updateComponentTreeUI(this);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelBase = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego Serpiente y Escalera\n");

        JPanelBase.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelBase;
    // End of variables declaration//GEN-END:variables
}
