/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cunoc.escaleraserpiente.componentesJuego;

/**
 *
 * @author drymnz
 */
public class PantallaDelJuego extends javax.swing.JPanel {

    /**
     * Creates new form PantallaDelJuego
     */
    public PantallaDelJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaPuntaje1 = new com.cunoc.escaleraserpiente.componentesJuego.TablaPuntaje();

        tablaPuntaje1.setBackground(new java.awt.Color(93, 195, 20));

        javax.swing.GroupLayout tablaPuntaje1Layout = new javax.swing.GroupLayout(tablaPuntaje1);
        tablaPuntaje1.setLayout(tablaPuntaje1Layout);
        tablaPuntaje1Layout.setHorizontalGroup(
            tablaPuntaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        tablaPuntaje1Layout.setVerticalGroup(
            tablaPuntaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(918, Short.MAX_VALUE)
                .addComponent(tablaPuntaje1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablaPuntaje1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.cunoc.escaleraserpiente.componentesJuego.TablaPuntaje tablaPuntaje1;
    // End of variables declaration//GEN-END:variables
}
