/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cunoc.escaleraserpiente.componentesJuego;

import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author drymnz
 */
public class Tablero extends javax.swing.JPanel {

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();

    }

    public void botones(int columna, int filas) {
        this.setLayout(new GridLayout(filas, columna));
        JPanel[][] listado = new JPanel[filas][columna];
        int contador = filas * columna;
        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columna; j++) {
                System.out.println(" " + contador + " ");
                listado[i][j] = new Casilla(i);
                listado[i][j].setBackground(((j+i)%2==0)?  Color.BLUE : Color.DARK_GRAY);
                this.add(listado[i][j]);
                contador--;
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(49, 127, 34));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
